import PageBaner from "@/components/share/PageBaner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { pageTitle } from "@/lib/type";
import { Label } from "@radix-ui/react-dropdown-menu";
import { Metadata } from "next";
import React from "react";
const pageTitleInfo: pageTitle = {
  pageTitle: "Contact Us",
  imgUrl: "/images/contact.png",
};
export const metadata: Metadata = {
  title: "Welcome to Travelaja | Home",
  description: "Generated by create next app",
};

const componentName = () => {
  return (
    <section>
      <PageBaner pageTitleInfo={pageTitleInfo} />
      <div className="max-w-screen-2xl px-3 mx-auto py-24 grid grid-cols-1 lg:grid-cols-2 gap-10">
        <div>
          <h1 className="font-bold py-5 text-3xl">Get in touch</h1>
          <p className="text-justify">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,
            purus sit amet luctus venenatis, lectus magna fringilla urna,
            porttitor rhoncus dolor purus non enim praesent elementum facilisis
            leo, vel fringilla est ullamcorper eget nulla facilisi etiam
            dignissim diam quis enim lobortis scelerisque fermentum dui faucibus
            in ornare quam viverra
          </p>
          <form className="mt-10" action="">
            <div className="grid w-full items-center gap-1.5">
              <Label>Name</Label>
              <Input type="text" id="email" placeholder="Input your name" />
            </div>
            <div className="grid w-full items-center gap-1.5 mt-5">
              <Label>Email</Label>
              <Input type="email" id="email" placeholder="Email" />
            </div>
            <div className="grid w-full items-center gap-1.5 mt-5">
              <Label>Message</Label>
              <Textarea placeholder="Type your massages" />
            </div>
            <Button className="text-white font-semibold mt-5" type="submit">
              {" "}
              Send
            </Button>
          </form>
        </div>
        <div>
          <div>
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3951.110113632684!2d112.5992067!3d-7.987563799999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7882bf109dd69f%3A0xbd24c94ea1679fb!2sJl.%20Cindelaras%2C%20Mulyorejo%2C%20Kec.%20Sukun%2C%20Kota%20Malang%2C%20Jawa%20Timur%2065147%2C%20Indonesia!5e0!3m2!1sen!2sbd!4v1730227619897!5m2!1sen!2sbd"
              width="100%"
              height="350"
              loading="lazy"
            ></iframe>
          </div>
          <div className="flex items-center justify-between mb-10">
            <p className="mt-10 leading-relaxed">
              <span className="font-bold">Address:</span> JL.Cindelaras No.205A,
              <br />
              <span className="font-bold">City: </span>Yogyakarta, Indonesia,
              <br />
              <span className="font-bold">Email:</span>info@travelaja.com,
              <br />
              <span className="font-bold">Phone:</span>+62 1234 432 567
            </p>
            <p>
              <span className="font-bold">Open:</span> 08.00 AM,
              <br />
              <span className="font-bold">Close:</span> 08.00 PM,
            </p>
          </div>
          <p className="font-bold text-2xl text-primary">
            AVAILABLE AT 9AM - 07PM
          </p>
          <p className="font-bold text-4xl">+124 4537 9756</p>
        </div>
      </div>
    </section>
  );
};

export default componentName;
